# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788fee62353082a712d0bd084b19b6299e7e333708942c4795e41321f8fbfaac037ab87a05a5df3f611a349bb117c26bd2a6e58e3a3be24b71d77e7c2c28803e

test:
  secret_key_base: 076b49a6f5ac4339021bd8737634ab7fb97b77123255a852c0fdd37bc4955f294d34a9a901312f3650f9233e651c4391c6fde1e1982b6b0c12384986523eae42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
